name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Check Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"

      - name: Check Terraform formatting
        working-directory: terraform
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init -backend=false

      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate